import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createJiti } from "jiti";

const jiti = createJiti(import.meta.url);
const { formatAgentEnvText, getAgentEnvOverrides, isDeniedAgentEnvName, parseAgentEnvText, sanitizeAgentEnvValues } =
  await jiti.import("./agent-env.ts");
const { sanitizeProjectCommandEnvironment } = await jiti.import("../project-command-env.ts");

/** Points getAgentDir() (and therefore the settings file) at a throwaway directory. */
function withAgentDir(run) {
  const dir = mkdtempSync(join(tmpdir(), "omp-web-agent-env-"));
  const previous = process.env.PI_CODING_AGENT_DIR;
  process.env.PI_CODING_AGENT_DIR = dir;
  try {
    run(dir);
  } finally {
    if (previous === undefined) delete process.env.PI_CODING_AGENT_DIR;
    else process.env.PI_CODING_AGENT_DIR = previous;
    delete globalThis.__ompWebSettingsCache;
    rmSync(dir, { recursive: true, force: true });
  }
}

function writeSettings(dir, contents) {
  writeFileSync(join(dir, "omp-web-settings.json"), typeof contents === "string" ? contents : JSON.stringify(contents), "utf8");
}

test("parses KEY=VALUE text, skipping blanks, comments and export prefixes", () => {
  const { values, errors } = parseAgentEnvText(
    ["# generated by NixOS", "", "OBSIDIAN_API_KEY=secret", "export HTTPS_PROXY=http://proxy.test:3128", "  SPACED = trimmed  ", "EMPTY="].join("\n"),
  );
  assert.deepEqual(errors, []);
  assert.deepEqual(values, {
    EMPTY: "",
    HTTPS_PROXY: "http://proxy.test:3128",
    OBSIDIAN_API_KEY: "secret",
    SPACED: "trimmed",
  });
});

test("keeps everything after the first '=' and tolerates CRLF", () => {
  const { values, errors } = parseAgentEnvText("DSN=user=me;pass=word\r\n\r\nEMPTY=\r\n");
  assert.deepEqual(errors, []);
  assert.deepEqual(values, { DSN: "user=me;pass=word", EMPTY: "" });
});

test("reports the offending line number for malformed input", () => {
  const { values, errors } = parseAgentEnvText(["A=1", "no-separator", "=novalue"].join("\n"));
  assert.deepEqual(values, { A: "1" });
  assert.equal(errors.length, 2);
  assert.match(errors[0], /^Line 2: /);
  assert.match(errors[1], /missing variable name/);
});

test("rejects names that are not shell identifiers", () => {
  for (const name of ["9LEADING", "WITH-DASH", "WITH.DOT", "WITH SPACE"]) {
    const { values, errors } = parseAgentEnvText(`${name}=x`);
    assert.deepEqual(values, {}, name);
    assert.equal(errors.length, 1, name);
    assert.match(errors[0], /not a valid variable name/);
  }
});

test("denies the plumbing omp-web and the spawner rely on", () => {
  // Minimum deny-list from issue #104 plus the host-runtime names that
  // sanitizeProjectCommandEnvironment() strips after the merge.
  const required = [
    "PATH", "NODE_OPTIONS", "SystemRoot", "SYSTEMROOT", "WINDIR", "COMSPEC", "PATHEXT",
    "PI_CODING_AGENT_DIR", "PI_CONFIG_DIR", "PORT", "HOSTNAME", "NODE_ENV", "HOME", "USERPROFILE",
    "OMP_WEB_PASSWORD", "NEXT_PUBLIC_FOO", "_PRIVATE",
  ];
  for (const name of required) {
    assert.equal(isDeniedAgentEnvName(name), true, name);
    const { values, errors } = parseAgentEnvText(`${name}=x`);
    assert.deepEqual(values, {}, name);
    assert.equal(errors.length, 1, name);
    assert.match(errors[0], /reserved by omp-web/);
  }
  assert.equal(isDeniedAgentEnvName("path"), true, "Windows names are case-insensitive");
  assert.equal(isDeniedAgentEnvName("OBSIDIAN_API_KEY"), false);
});

test("standalone host and port do not leak into omp's project commands", () => {
  const env = { PORT: "30177", HOSTNAME: "127.0.0.1", NODE_ENV: "production", NEXT_RUNTIME: "nodejs", HTTPS_PROXY: "http://proxy.test", OMP_WEB_OMP_BIN: "/real/omp" };
  assert.deepEqual(sanitizeProjectCommandEnvironment(env, "darwin"), { HTTPS_PROXY: "http://proxy.test", OMP_WEB_OMP_BIN: "/real/omp" });
  assert.deepEqual(sanitizeProjectCommandEnvironment({ port: "30177", hostname: "127.0.0.1", Path: "C:\\bin" }, "win32"), { Path: "C:\\bin" });
});

test("a denied line is reported but never reaches values", () => {
  const { values, errors } = parseAgentEnvText("PATH=/tmp/evil\nOMP_WEB_TOKEN=leak\nGOOD=1");
  assert.deepEqual(values, { GOOD: "1" });
  assert.equal(errors.length, 2);
  assert.match(errors[0], /"PATH"/);
  assert.match(errors[1], /"OMP_WEB_TOKEN"/);
});

test("later assignments win, like a shell", () => {
  const { values, errors } = parseAgentEnvText("KEY=first\nKEY=second");
  assert.deepEqual(values, { KEY: "second" });
  assert.deepEqual(errors, []);
});

test("formatAgentEnvText sorts keys so saves are stable, and round-trips", () => {
  const values = { ZED: "3", ALPHA: "1", MIDDLE: "2" };
  const text = formatAgentEnvText(values);
  assert.equal(text, "ALPHA=1\nMIDDLE=2\nZED=3");
  assert.deepEqual(parseAgentEnvText(text).values, values);
  assert.equal(formatAgentEnvText({}), "");
});

test("custom labels replace the English messages (used by the settings UI)", () => {
  const { errors } = parseAgentEnvText("PATH=x\nBAD-NAME=y", {
    deniedName: (line, name) => `denied:${line}:${name}`,
    invalidName: (line, name) => `invalid:${line}:${name}`,
  });
  assert.deepEqual(errors, ["denied:1:PATH", "invalid:2:BAD-NAME"]);
});

test("sanitizeAgentEnvValues drops non-strings and reserved names", () => {
  const result = sanitizeAgentEnvValues({ GOOD: "1", NUM: 2, NESTED: { a: 1 }, PATH: "/evil" });
  assert.deepEqual(result.values, { GOOD: "1" });
  assert.equal(result.errors.length, 1);
  assert.deepEqual(sanitizeAgentEnvValues("not a record").values, {});
  assert.deepEqual(sanitizeAgentEnvValues(null).values, {});
});

test("getAgentEnvOverrides returns {} when no settings file exists", () => {
  withAgentDir(() => {
    assert.deepEqual(getAgentEnvOverrides(), {});
  });
});

test("getAgentEnvOverrides reads persisted values and drops reserved ones", () => {
  withAgentDir((dir) => {
    writeSettings(dir, { autoResumeSessions: true, agentEnv: { OBSIDIAN_API_KEY: "secret", PATH: "/evil", OMP_WEB_TOKEN: "leak" } });
    assert.deepEqual(getAgentEnvOverrides(), { OBSIDIAN_API_KEY: "secret" });
  });
});

test("getAgentEnvOverrides survives a corrupt settings file", () => {
  withAgentDir((dir) => {
    writeSettings(dir, "{ not json");
    assert.deepEqual(getAgentEnvOverrides(), {});
  });
});

test("getAgentEnvOverrides ignores a non-object agentEnv", () => {
  withAgentDir((dir) => {
    writeSettings(dir, { autoResumeSessions: false, agentEnv: "OBSIDIAN_API_KEY=secret" });
    assert.deepEqual(getAgentEnvOverrides(), {});
    // …and the file on disk is untouched by the read.
    assert.match(readFileSync(join(dir, "omp-web-settings.json"), "utf8"), /OBSIDIAN_API_KEY=secret/);
  });
});