import AppKit
import WebKit

struct BrowserTarget: Hashable, Sendable {
    let paneId: String
    let tabId: String
}

enum BrowserAddressResolver {
    static func resolve(_ input: String) -> URL? {
        let trimmed = input.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        let lowercased = trimmed.lowercased()
        let isLocal = lowercased == "localhost"
            || lowercased.hasPrefix("localhost:")
            || lowercased == "127.0.0.1"
            || lowercased.hasPrefix("127.0.0.1:")
            || lowercased == "0.0.0.0"
            || lowercased.hasPrefix("0.0.0.0:")
            || lowercased == "[::1]"
            || lowercased.hasPrefix("[::1]:")
        if isLocal {
            return URL(string: "http://\(trimmed)")
        }

        if let url = URL(string: trimmed), url.scheme != nil {
            return url
        }

        if !trimmed.contains(where: \.isWhitespace),
           trimmed.contains(".") || trimmed.contains(":")
        {
            return URL(string: "https://\(trimmed)")
        }

        var components = URLComponents(string: "https://duckduckgo.com/")
        components?.queryItems = [URLQueryItem(name: "q", value: trimmed)]
        return components?.url
    }
}

@MainActor
final class BrowserPaneRegistry {
    static let shared = BrowserPaneRegistry()

    private final class WeakView {
        weak var value: BrowserPaneView?

        init(_ value: BrowserPaneView) {
            self.value = value
        }
    }

    private var views: [BrowserTarget: WeakView] = [:]

    func register(_ view: BrowserPaneView) {
        prune()
        views[view.target] = WeakView(view)
    }

    func unregister(_ view: BrowserPaneView) {
        guard views[view.target]?.value === view else { return }
        views.removeValue(forKey: view.target)
    }

    func view(for target: BrowserTarget) -> BrowserPaneView? {
        prune()
        return views[target]?.value
    }

    private func prune() {
        views = views.filter { $0.value.value != nil }
    }
}

enum BrowserAutomationError: LocalizedError {
    case invalidArguments(String)
    case elementNotFound(String)
    case javascript(String)
    case screenshot(String)

    var errorDescription: String? {
        switch self {
        case .invalidArguments(let usage):
            return usage
        case .elementNotFound(let selector):
            return "Element not found: \(selector)"
        case .javascript(let message), .screenshot(let message):
            return message
        }
    }
}

/// A native browser tab backed by WKWebView. Its small automation surface uses
/// agent-browser-style ephemeral element refs (`@e1`, `@e2`, …) generated by
/// `snapshot`.
@MainActor
final class BrowserPaneView: NSView, WKNavigationDelegate, WKUIDelegate, NSTextFieldDelegate {
    let target: BrowserTarget
    var onFocusRequested: (() -> Void)?
    var onTitleChanged: ((String) -> Void)?
    var onURLChanged: ((String) -> Void)?

    private let themeManager: ThemeManager
    private let webView: SopranoWebView
    private let navigationBar = NSView()
    private let addressField = NSTextField()
    private let backButton = NSButton()
    private let forwardButton = NSButton()
    private let reloadButton = NSButton()
    private let progressIndicator = NSProgressIndicator()
    private var hasLoadedLocation = false

    init(
        target: BrowserTarget,
        initialURL: String? = nil,
        themeManager: ThemeManager
    ) {
        self.target = target
        self.themeManager = themeManager

        let configuration = WKWebViewConfiguration()
        configuration.websiteDataStore = .default()
        configuration.defaultWebpagePreferences.allowsContentJavaScript = true
        configuration.preferences.isElementFullscreenEnabled = true
        self.webView = SopranoWebView(frame: .zero, configuration: configuration)

        super.init(frame: .zero)
        setupViews()
        BrowserPaneRegistry.shared.register(self)

        if let initialURL, let url = BrowserAddressResolver.resolve(initialURL) {
            load(url)
        }
    }

    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) is not supported")
    }

    deinit {
        MainActor.assumeIsolated {
            BrowserPaneRegistry.shared.unregister(self)
        }
    }

    func applyTheme() {
        let theme = themeManager.currentTheme
        layer?.backgroundColor = theme.colors.bgBase.cgColor
        navigationBar.layer?.backgroundColor = theme.colors.bgPanel.cgColor
        addressField.backgroundColor = theme.colors.bgBase
        addressField.textColor = theme.colors.textPrimary
        addressField.placeholderString = "Search or enter address"
        backButton.contentTintColor = theme.colors.textMuted
        forwardButton.contentTintColor = theme.colors.textMuted
        reloadButton.contentTintColor = theme.colors.textMuted
        progressIndicator.contentFilters = []
    }

    func focusPreferredControl() {
        guard let window else { return }
        if hasLoadedLocation {
            window.makeFirstResponder(webView)
        } else {
            focusAddressBar()
        }
    }

    func focusAddressBar() {
        onFocusRequested?()
        window?.makeFirstResponder(addressField)
        addressField.currentEditor()?.selectAll(nil)
    }

    func navigate(to input: String) throws -> String {
        guard let url = BrowserAddressResolver.resolve(input) else {
            throw BrowserAutomationError.invalidArguments("Invalid browser address: \(input)")
        }
        load(url)
        return url.absoluteString
    }

    func performAutomation(
        command: String,
        arguments: [String],
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        switch command {
        case "goto", "navigate":
            guard let input = arguments.first else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser \(command) <url>"
                )))
                return
            }
            do {
                completion(.success(try navigate(to: input)))
            } catch {
                completion(.failure(error))
            }

        case "back":
            webView.goBack()
            completion(.success(webView.url?.absoluteString ?? ""))

        case "forward":
            webView.goForward()
            completion(.success(webView.url?.absoluteString ?? ""))

        case "reload":
            webView.reload()
            completion(.success(webView.url?.absoluteString ?? ""))

        case "url", "get-url":
            completion(.success(webView.url?.absoluteString ?? ""))

        case "title":
            completion(.success(webView.title ?? ""))

        case "focus-address":
            focusAddressBar()
            completion(.success("focused address bar"))

        case "snapshot":
            evaluateString(
                Self.snapshotScript(interactiveOnly: arguments.contains("--interactive")),
                completion: completion
            )

        case "eval":
            guard !arguments.isEmpty else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser eval <javascript>"
                )))
                return
            }
            evaluateJavaScript(arguments.joined(separator: " "), completion: completion)

        case "click", "dblclick", "focus", "hover", "check", "uncheck",
             "scroll-into-view":
            guard let selector = arguments.first else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser \(command) <selector|@ref>"
                )))
                return
            }
            evaluateAction(
                Self.elementActionScript(command: command, selector: selector),
                selector: selector,
                completion: completion
            )

        case "fill", "type":
            guard let selector = arguments.first else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser \(command) <selector|@ref> <text>"
                )))
                return
            }
            let text = arguments.dropFirst().joined(separator: " ")
            evaluateAction(
                Self.textActionScript(command: command, selector: selector, text: text),
                selector: selector,
                completion: completion
            )

        case "press":
            guard let key = arguments.first else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser press <key>"
                )))
                return
            }
            evaluateAction(
                Self.keyPressScript(key: key),
                selector: key,
                completion: completion
            )

        case "get":
            performGet(arguments: arguments, completion: completion)

        case "is":
            performStateCheck(arguments: arguments, completion: completion)

        case "screenshot":
            guard let path = arguments.first else {
                completion(.failure(BrowserAutomationError.invalidArguments(
                    "Usage: soprano browser screenshot <path.png>"
                )))
                return
            }
            takeScreenshot(path: path, completion: completion)

        default:
            completion(.failure(BrowserAutomationError.invalidArguments(
                "Unsupported browser command: \(command)"
            )))
        }
    }

    private func setupViews() {
        wantsLayer = true
        navigationBar.wantsLayer = true
        navigationBar.translatesAutoresizingMaskIntoConstraints = false
        addSubview(navigationBar)

        configureButton(
            backButton,
            symbol: "chevron.left",
            toolTip: "Back",
            action: #selector(goBack)
        )
        configureButton(
            forwardButton,
            symbol: "chevron.right",
            toolTip: "Forward",
            action: #selector(goForward)
        )
        configureButton(
            reloadButton,
            symbol: "arrow.clockwise",
            toolTip: "Reload",
            action: #selector(reloadPage)
        )

        addressField.font = .systemFont(ofSize: 12)
        addressField.isBezeled = true
        addressField.bezelStyle = .roundedBezel
        addressField.focusRingType = .none
        addressField.target = self
        addressField.action = #selector(addressSubmitted)
        addressField.delegate = self
        addressField.translatesAutoresizingMaskIntoConstraints = false
        navigationBar.addSubview(addressField)

        progressIndicator.style = .spinning
        progressIndicator.controlSize = .small
        progressIndicator.isDisplayedWhenStopped = false
        progressIndicator.translatesAutoresizingMaskIntoConstraints = false
        navigationBar.addSubview(progressIndicator)

        webView.navigationDelegate = self
        webView.uiDelegate = self
        webView.allowsMagnification = true
        webView.isInspectable = true
        webView.onFocusRequested = { [weak self] in
            self?.onFocusRequested?()
        }
        webView.onFocusAddressRequested = { [weak self] in
            self?.focusAddressBar()
        }
        webView.onBackRequested = { [weak self] in
            self?.goBack()
        }
        webView.onForwardRequested = { [weak self] in
            self?.goForward()
        }
        webView.onReloadRequested = { [weak self] in
            self?.reloadPage()
        }
        webView.translatesAutoresizingMaskIntoConstraints = false
        addSubview(webView)

        NSLayoutConstraint.activate([
            navigationBar.topAnchor.constraint(equalTo: topAnchor),
            navigationBar.leadingAnchor.constraint(equalTo: leadingAnchor),
            navigationBar.trailingAnchor.constraint(equalTo: trailingAnchor),
            navigationBar.heightAnchor.constraint(equalToConstant: 38),

            backButton.leadingAnchor.constraint(equalTo: navigationBar.leadingAnchor, constant: 5),
            backButton.centerYAnchor.constraint(equalTo: navigationBar.centerYAnchor),
            backButton.widthAnchor.constraint(equalToConstant: 26),
            backButton.heightAnchor.constraint(equalToConstant: 26),

            forwardButton.leadingAnchor.constraint(equalTo: backButton.trailingAnchor),
            forwardButton.centerYAnchor.constraint(equalTo: navigationBar.centerYAnchor),
            forwardButton.widthAnchor.constraint(equalToConstant: 26),
            forwardButton.heightAnchor.constraint(equalToConstant: 26),

            reloadButton.leadingAnchor.constraint(equalTo: forwardButton.trailingAnchor),
            reloadButton.centerYAnchor.constraint(equalTo: navigationBar.centerYAnchor),
            reloadButton.widthAnchor.constraint(equalToConstant: 26),
            reloadButton.heightAnchor.constraint(equalToConstant: 26),

            addressField.leadingAnchor.constraint(equalTo: reloadButton.trailingAnchor, constant: 6),
            addressField.trailingAnchor.constraint(equalTo: progressIndicator.leadingAnchor, constant: -7),
            addressField.centerYAnchor.constraint(equalTo: navigationBar.centerYAnchor),
            addressField.heightAnchor.constraint(equalToConstant: 25),

            progressIndicator.trailingAnchor.constraint(
                equalTo: navigationBar.trailingAnchor,
                constant: -9
            ),
            progressIndicator.centerYAnchor.constraint(equalTo: navigationBar.centerYAnchor),
            progressIndicator.widthAnchor.constraint(equalToConstant: 14),
            progressIndicator.heightAnchor.constraint(equalToConstant: 14),

            webView.topAnchor.constraint(equalTo: navigationBar.bottomAnchor),
            webView.leadingAnchor.constraint(equalTo: leadingAnchor),
            webView.trailingAnchor.constraint(equalTo: trailingAnchor),
            webView.bottomAnchor.constraint(equalTo: bottomAnchor),
        ])

        applyTheme()
        updateNavigationControls()
    }

    private func configureButton(
        _ button: NSButton,
        symbol: String,
        toolTip: String,
        action: Selector
    ) {
        button.title = ""
        button.target = self
        button.action = action
        button.isBordered = false
        button.image = NSImage(
            systemSymbolName: symbol,
            accessibilityDescription: toolTip
        )
        button.imagePosition = .imageOnly
        button.toolTip = toolTip
        button.translatesAutoresizingMaskIntoConstraints = false
        navigationBar.addSubview(button)
    }

    private func load(_ url: URL) {
        hasLoadedLocation = true
        addressField.stringValue = url.absoluteString
        onURLChanged?(url.absoluteString)
        webView.load(URLRequest(url: url))
    }

    @objc private func goBack() {
        onFocusRequested?()
        webView.goBack()
    }

    @objc private func goForward() {
        onFocusRequested?()
        webView.goForward()
    }

    @objc private func reloadPage() {
        onFocusRequested?()
        if webView.isLoading {
            webView.stopLoading()
        } else {
            webView.reload()
        }
    }

    @objc private func addressSubmitted() {
        do {
            _ = try navigate(to: addressField.stringValue)
            window?.makeFirstResponder(webView)
        } catch {
            NSSound.beep()
        }
    }

    func controlTextDidBeginEditing(_ notification: Notification) {
        // AppKit is still assigning its field editor here. Updating the pane
        // model synchronously can make SplitTreeView try to restore keyboard
        // focus reentrantly.
        DispatchQueue.main.async { [weak self] in
            self?.onFocusRequested?()
        }
    }

    func webView(_ webView: WKWebView, didStartProvisionalNavigation navigation: WKNavigation!) {
        progressIndicator.startAnimation(nil)
        updateLocation(from: webView)
        updateNavigationControls()
    }

    func webView(_ webView: WKWebView, didCommit navigation: WKNavigation!) {
        updateLocation(from: webView)
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        progressIndicator.stopAnimation(nil)
        updateLocation(from: webView)
        updateNavigationControls()
        if let title = webView.title?.trimmingCharacters(in: .whitespacesAndNewlines),
           !title.isEmpty
        {
            onTitleChanged?(title)
        }
    }

    func webView(
        _ webView: WKWebView,
        didFail navigation: WKNavigation!,
        withError error: Error
    ) {
        progressIndicator.stopAnimation(nil)
        updateNavigationControls()
    }

    func webView(
        _ webView: WKWebView,
        didFailProvisionalNavigation navigation: WKNavigation!,
        withError error: Error
    ) {
        progressIndicator.stopAnimation(nil)
        updateNavigationControls()
    }

    func webView(
        _ webView: WKWebView,
        createWebViewWith configuration: WKWebViewConfiguration,
        for navigationAction: WKNavigationAction,
        windowFeatures: WKWindowFeatures
    ) -> WKWebView? {
        if navigationAction.targetFrame == nil, let url = navigationAction.request.url {
            load(url)
        }
        return nil
    }

    private func updateLocation(from webView: WKWebView) {
        guard let value = webView.url?.absoluteString, !value.isEmpty else { return }
        hasLoadedLocation = true
        addressField.stringValue = value
        onURLChanged?(value)
    }

    private func updateNavigationControls() {
        backButton.isEnabled = webView.canGoBack
        forwardButton.isEnabled = webView.canGoForward
        reloadButton.image = NSImage(
            systemSymbolName: webView.isLoading ? "xmark" : "arrow.clockwise",
            accessibilityDescription: webView.isLoading ? "Stop" : "Reload"
        )
    }

    private func evaluateJavaScript(
        _ script: String,
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        webView.evaluateJavaScript(script) { value, error in
            if let error {
                completion(.failure(BrowserAutomationError.javascript(error.localizedDescription)))
                return
            }
            completion(.success(Self.printableJavaScriptValue(value)))
        }
    }

    private func evaluateString(
        _ script: String,
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        webView.evaluateJavaScript(script) { value, error in
            if let error {
                completion(.failure(BrowserAutomationError.javascript(error.localizedDescription)))
            } else {
                completion(.success(value as? String ?? ""))
            }
        }
    }

    private func evaluateAction(
        _ script: String,
        selector: String,
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        webView.evaluateJavaScript(script) { value, error in
            if let error {
                completion(.failure(BrowserAutomationError.javascript(error.localizedDescription)))
                return
            }
            guard let payload = value as? [String: Any],
                  payload["ok"] as? Bool == true
            else {
                let message = (value as? [String: Any])?["error"] as? String
                completion(.failure(
                    message.map(BrowserAutomationError.javascript)
                        ?? BrowserAutomationError.elementNotFound(selector)
                ))
                return
            }
            completion(.success(payload["output"] as? String ?? "ok"))
        }
    }

    private func performGet(
        arguments: [String],
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        guard arguments.count >= 2 else {
            completion(.failure(BrowserAutomationError.invalidArguments(
                "Usage: soprano browser get <text|html|value|attr|count> <selector> [attribute]"
            )))
            return
        }
        let kind = arguments[0]
        let selector = arguments[1]
        let attribute = arguments.count > 2 ? arguments[2] : nil
        evaluateAction(
            Self.getScript(kind: kind, selector: selector, attribute: attribute),
            selector: selector,
            completion: completion
        )
    }

    private func performStateCheck(
        arguments: [String],
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        guard arguments.count >= 2 else {
            completion(.failure(BrowserAutomationError.invalidArguments(
                "Usage: soprano browser is <visible|enabled|checked> <selector|@ref>"
            )))
            return
        }
        evaluateAction(
            Self.stateScript(kind: arguments[0], selector: arguments[1]),
            selector: arguments[1],
            completion: completion
        )
    }

    private func takeScreenshot(
        path: String,
        completion: @escaping (Result<String, Error>) -> Void
    ) {
        webView.takeSnapshot(with: nil) { image, error in
            if let error {
                completion(.failure(BrowserAutomationError.screenshot(error.localizedDescription)))
                return
            }
            guard let image,
                  let tiff = image.tiffRepresentation,
                  let bitmap = NSBitmapImageRep(data: tiff),
                  let png = bitmap.representation(using: .png, properties: [:])
            else {
                completion(.failure(BrowserAutomationError.screenshot(
                    "WebKit could not encode the screenshot"
                )))
                return
            }

            do {
                let url = URL(fileURLWithPath: path)
                try FileManager.default.createDirectory(
                    at: url.deletingLastPathComponent(),
                    withIntermediateDirectories: true
                )
                try png.write(to: url, options: .atomic)
                completion(.success(url.path))
            } catch {
                completion(.failure(BrowserAutomationError.screenshot(error.localizedDescription)))
            }
        }
    }

    private static func printableJavaScriptValue(_ value: Any?) -> String {
        guard let value else { return "null" }
        if JSONSerialization.isValidJSONObject(value),
           let data = try? JSONSerialization.data(
               withJSONObject: value,
               options: [.prettyPrinted, .sortedKeys]
           ),
           let json = String(data: data, encoding: .utf8)
        {
            return json
        }
        return String(describing: value)
    }

    private static func literal(_ value: String) -> String {
        guard let data = try? JSONEncoder().encode(value),
              let literal = String(data: data, encoding: .utf8)
        else {
            return "\"\""
        }
        return literal
    }

    private static func resolverPrelude(selector: String) -> String {
        """
        const selector = \(literal(selector));
        const resolve = (value) => {
          if (value.startsWith('@')) {
            return window.__sopranoElementRefs?.[value.slice(1)] || null;
          }
          try { return document.querySelector(value); } catch (_) { return null; }
        };
        const element = resolve(selector);
        if (!element) return {ok: false, error: `Element not found: ${selector}`};
        """
    }

    private static func elementActionScript(command: String, selector: String) -> String {
        let action: String
        switch command {
        case "click":
            action = "element.click();"
        case "dblclick":
            action = """
            element.dispatchEvent(new MouseEvent('dblclick', {bubbles: true, cancelable: true, view: window}));
            """
        case "focus":
            action = "element.focus();"
        case "hover":
            action = """
            element.dispatchEvent(new MouseEvent('mouseover', {bubbles: true, view: window}));
            element.dispatchEvent(new MouseEvent('mouseenter', {bubbles: false, view: window}));
            """
        case "check":
            action = """
            if (!('checked' in element)) return {ok: false, error: 'Element is not checkable'};
            element.checked = true;
            element.dispatchEvent(new Event('input', {bubbles: true}));
            element.dispatchEvent(new Event('change', {bubbles: true}));
            """
        case "uncheck":
            action = """
            if (!('checked' in element)) return {ok: false, error: 'Element is not checkable'};
            element.checked = false;
            element.dispatchEvent(new Event('input', {bubbles: true}));
            element.dispatchEvent(new Event('change', {bubbles: true}));
            """
        case "scroll-into-view":
            action = "element.scrollIntoView({block: 'center', inline: 'center'});"
        default:
            action = ""
        }

        return """
        (() => {
          \(resolverPrelude(selector: selector))
          element.scrollIntoView({block: 'center', inline: 'center'});
          \(action)
          return {ok: true, output: \(literal("\(command) \(selector)"))};
        })()
        """
    }

    private static func textActionScript(command: String, selector: String, text: String) -> String {
        let assignment = command == "fill"
            ? "element.value = text;"
            : "element.value = String(element.value || '') + text;"
        return """
        (() => {
          \(resolverPrelude(selector: selector))
          const text = \(literal(text));
          element.focus();
          if (element.isContentEditable) {
            element.textContent = \(command == "fill" ? "text" : "String(element.textContent || '') + text");
          } else if ('value' in element) {
            \(assignment)
          } else {
            return {ok: false, error: 'Element is not editable'};
          }
          element.dispatchEvent(new InputEvent('input', {bubbles: true, inputType: 'insertText', data: text}));
          element.dispatchEvent(new Event('change', {bubbles: true}));
          return {ok: true, output: \(literal("\(command) \(selector)"))};
        })()
        """
    }

    private static func keyPressScript(key: String) -> String {
        """
        (() => {
          const element = document.activeElement || document.body;
          const key = \(literal(key));
          const aliases = {Enter: 'Enter', Escape: 'Escape', Tab: 'Tab', Space: ' '};
          const resolved = aliases[key] || key;
          element.dispatchEvent(new KeyboardEvent('keydown', {key: resolved, bubbles: true, cancelable: true}));
          if (resolved === 'Enter') {
            if (element.form?.requestSubmit) element.form.requestSubmit();
            else if (element.click) element.click();
          } else if (resolved.length === 1 && 'value' in element) {
            element.value = String(element.value || '') + resolved;
            element.dispatchEvent(new InputEvent('input', {bubbles: true, data: resolved}));
          }
          element.dispatchEvent(new KeyboardEvent('keyup', {key: resolved, bubbles: true, cancelable: true}));
          return {ok: true, output: `pressed ${key}`};
        })()
        """
    }

    private static func getScript(kind: String, selector: String, attribute: String?) -> String {
        let expression: String
        switch kind {
        case "text":
            expression = "element.innerText ?? element.textContent ?? ''"
        case "html":
            expression = "element.outerHTML"
        case "value":
            expression = "element.value ?? ''"
        case "attr":
            expression = "element.getAttribute(\(literal(attribute ?? ""))) ?? ''"
        case "count":
            return """
            (() => {
              const selector = \(literal(selector));
              if (selector.startsWith('@')) {
                return {ok: true, output: window.__sopranoElementRefs?.[selector.slice(1)] ? '1' : '0'};
              }
              try {
                return {ok: true, output: String(document.querySelectorAll(selector).length)};
              } catch (_) {
                return {ok: false, error: `Invalid selector: ${selector}`};
              }
            })()
            """
        default:
            return "({ok: false, error: \(literal("Unsupported getter: \(kind)"))})"
        }

        return """
        (() => {
          \(resolverPrelude(selector: selector))
          return {ok: true, output: String(\(expression))};
        })()
        """
    }

    private static func stateScript(kind: String, selector: String) -> String {
        let expression: String
        switch kind {
        case "visible":
            expression = """
            (() => {
              const style = getComputedStyle(element);
              const rect = element.getBoundingClientRect();
              return style.visibility !== 'hidden' && style.display !== 'none' &&
                rect.width > 0 && rect.height > 0;
            })()
            """
        case "enabled":
            expression = "!element.disabled && element.getAttribute('aria-disabled') !== 'true'"
        case "checked":
            expression = "Boolean(element.checked || element.getAttribute('aria-checked') === 'true')"
        default:
            return "({ok: false, error: \(literal("Unsupported state check: \(kind)"))})"
        }
        return """
        (() => {
          \(resolverPrelude(selector: selector))
          return {ok: true, output: String(Boolean(\(expression)))};
        })()
        """
    }

    private static func snapshotScript(interactiveOnly: Bool) -> String {
        """
        (() => {
          window.__sopranoElementRefs = {};
          let nextRef = 1;
          const interactiveOnly = \(interactiveOnly ? "true" : "false");
          const implicitRoles = {
            A: 'link', BUTTON: 'button', INPUT: 'textbox', SELECT: 'combobox',
            TEXTAREA: 'textbox', IMG: 'img', H1: 'heading', H2: 'heading',
            H3: 'heading', H4: 'heading', H5: 'heading', H6: 'heading',
            LI: 'listitem', OPTION: 'option', SUMMARY: 'button'
          };
          const interactiveRoles = new Set([
            'button', 'link', 'textbox', 'searchbox', 'combobox', 'checkbox',
            'radio', 'slider', 'spinbutton', 'switch', 'tab', 'menuitem', 'option'
          ]);
          const visible = (element) => {
            const style = getComputedStyle(element);
            const rect = element.getBoundingClientRect();
            return style.visibility !== 'hidden' && style.display !== 'none' &&
              rect.width > 0 && rect.height > 0;
          };
          const roleFor = (element) => {
            const explicit = element.getAttribute('role');
            if (explicit) return explicit;
            if (element.tagName === 'INPUT') {
              const type = (element.getAttribute('type') || 'text').toLowerCase();
              if (type === 'checkbox') return 'checkbox';
              if (type === 'radio') return 'radio';
              if (['button', 'submit', 'reset'].includes(type)) return 'button';
              if (type === 'range') return 'slider';
              if (type === 'search') return 'searchbox';
            }
            return implicitRoles[element.tagName] || '';
          };
          const nameFor = (element) => {
            const labelledBy = element.getAttribute('aria-labelledby');
            if (labelledBy) {
              const text = labelledBy.split(/\\s+/).map((id) =>
                document.getElementById(id)?.innerText || ''
              ).join(' ').trim();
              if (text) return text;
            }
            const aria = element.getAttribute('aria-label');
            if (aria) return aria.trim();
            if (element.labels?.length) {
              const text = Array.from(element.labels).map((label) => label.innerText).join(' ').trim();
              if (text) return text;
            }
            return (
              element.getAttribute('alt') ||
              element.getAttribute('title') ||
              element.getAttribute('placeholder') ||
              element.value ||
              element.innerText ||
              element.textContent ||
              ''
            ).replace(/\\s+/g, ' ').trim().slice(0, 160);
          };
          const lines = [];
          for (const element of document.querySelectorAll('*')) {
            if (!visible(element)) continue;
            const role = roleFor(element);
            if (!role) continue;
            const interactive = interactiveRoles.has(role) ||
              element.matches('a[href],button,input,select,textarea,[tabindex]:not([tabindex="-1"])');
            if (interactiveOnly && !interactive) continue;
            const name = nameFor(element).replaceAll('"', '\\\\"');
            let suffix = '';
            if (interactive) {
              const ref = `e${nextRef++}`;
              window.__sopranoElementRefs[ref] = element;
              suffix += ` [ref=${ref}]`;
            }
            if (role === 'heading' && /^H[1-6]$/.test(element.tagName)) {
              suffix += ` [level=${element.tagName.slice(1)}]`;
            }
            if (element.disabled || element.getAttribute('aria-disabled') === 'true') {
              suffix += ' [disabled]';
            }
            if (element.checked || element.getAttribute('aria-checked') === 'true') {
              suffix += ' [checked]';
            }
            lines.push(`- ${role}${name ? ` "${name}"` : ''}${suffix}`);
          }
          return lines.length ? lines.join('\\n') : '(no accessible elements)';
        })()
        """
    }
}

@MainActor
private final class SopranoWebView: WKWebView {
    var onFocusRequested: (() -> Void)?
    var onFocusAddressRequested: (() -> Void)?
    var onBackRequested: (() -> Void)?
    var onForwardRequested: (() -> Void)?
    var onReloadRequested: (() -> Void)?

    override func becomeFirstResponder() -> Bool {
        let accepted = super.becomeFirstResponder()
        if accepted {
            // Let AppKit finish assigning the first responder before focusing
            // the model. The ensuing layout notification may otherwise try to
            // make this view first responder reentrantly.
            DispatchQueue.main.async { [weak self] in
                self?.onFocusRequested?()
            }
        }
        return accepted
    }

    override func performKeyEquivalent(with event: NSEvent) -> Bool {
        let modifiers = event.modifierFlags.intersection(.deviceIndependentFlagsMask)
        guard modifiers == .command || modifiers == [.command, .shift],
              let key = event.charactersIgnoringModifiers?.lowercased()
        else {
            return super.performKeyEquivalent(with: event)
        }

        switch key {
        case "l":
            onFocusAddressRequested?()
        case "[":
            onBackRequested?()
        case "]":
            onForwardRequested?()
        case "r":
            onReloadRequested?()
        default:
            return super.performKeyEquivalent(with: event)
        }
        return true
    }
}
